version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: sanic_app
    restart: always
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres_db:5432/test_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/app
    command: ["python", "main.py"]

volumes:
  postgres_data: